version: '3.3'

services:

  db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    container_name: 'db'
    env_file:
      - ./.env

  backend:
    image: photometer/foodgram:v1
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
    container_name: 'backend'
    env_file:
      - ./.env

  frontend:
    image: photometer/foodgram_frontend:v1
    volumes:
      - ./frontend/:/app/result_build/
    container_name: 'frontend'

  nginx:
    image: nginx:1.19.3

    ports:
      - "80:80"
      - "443:443"

    restart: always

    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      - backend

    container_name: 'nginx'

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx
    container_name: 'certbot'

volumes:
  static_value:
  media_value:
