# Generated by Django 2.2.16 on 2022-05-29 13:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20220526_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredientrecipe',
            name='amount',
            field=models.PositiveSmallIntegerField(error_messages={'validators': 'Введите значение больше 0!'}, validators=[django.core.validators.MinValueValidator(limit_value=1, message='Введите значение больше 0!')], verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(error_messages={'validators': 'Введите значение больше 0!'}, help_text='Время в минутах', validators=[django.core.validators.MinValueValidator(limit_value=1, message='Введите значение больше 0!')], verbose_name='Время приготовления в минутах'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(error_messages={'validators': 'Неверное значение HEX-кода'}, max_length=7, unique=True, validators=[django.core.validators.RegexValidator(message='Неверное значение HEX-кода', regex='^#[a-fA-F0-9]{6}$')], verbose_name='HEX-код цвета'),
        ),
    ]
